### ISSUE TITLE
Allow multiple KSS documentation blocks per file/partial

### ISSUE THREAD

**Issue by ostowe** [alleyinteractive/huron#48]
Currently Huron will get confused if there are multiple KSS doc blocks in a single file or SCSS partial. This may be a fairly complex feature, but I'll set it for a `0.1.1` milestone anyway and we can re-evaluate once someone has done some research.

**Comment by pattiereaves** [comment]
Do you think this is a feature worth supporting? I feel like multiple KSS blocks per file is a poor idea for code maintenance.

**Comment by ostowe** [comment]
Yeah, I'm inclined to agree. One of the whole points of this update is to eliminate the need for multiple KSS blocks per file. I say we just close this for now and reopen if we change our minds for some reason.
