### ISSUE TITLE
Huron won't build when the output folder does not exist

### ISSUE THREAD

**Issue by pattiereaves** [alleyinteractive/huron#83]
In setting up Huron for the first time, I got this error
```
ERROR in ./static/prototype/huron-assets/huron.js
Module not found: Error: Can't resolve '../partials' in '/Users/pattie/broadway/www/huronforwordpress/wp-content/themes/huronforwp/static/prototype/huron-assets'
 @ ./static/prototype/huron-assets/huron.js 16:22-20:7
 @ multi webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./static/prototype/huron-assets/huron ./client/js/global.js
```
where the folder defined in "output" had not been created yet.

**Comment by ian-pvd** [comment]
Marking this as "can't replicate"

Was not able to trigger the same error message using the following steps.

1. set up `huron-examples` repo
2. changed `output` value to `'there-had-better-be-cat-photos'` (in hopes that this was a unique file path)
2. Ran `npm run huron`

Also tried:
1. Set up `huron-examples` repo
2. Ran `rm -rf static/` to delete the output folder
3. Ran `npm run huron`
