### ISSUE TITLE
Remove jsmd5 dependency

### ISSUE THREAD

**Issue by ostowe** [alleyinteractive/huron#85]
`jsmd5` is _massive_, and we're only using it for one tiny thing. If possible, we should come up with a way to create unique string for the same purpose without an md5 hash.

**Comment by FStop** [comment]
@ostowe I know very little about this, but googling `node md5` brought up [a gist](https://gist.github.com/kitek/1579117), and a [SO question](https://stackoverflow.com/questions/5878682/node-js-hash-string), which but suggest Node's `crypto` module.

**Comment by FStop** [comment]
I guess I could take a crack at this and see where it leads me...

**Comment by ostowe** [comment]
Cool, yeah `crypto` might be a good option. The thing to keep in mind here is it just needs to be a unique string, doesn't actually have anything to do with security.

**Comment by FStop** [comment]
Thanks, @ostowe, that makes sense. Side question: what's the best way to console log things with Huron...?

In this case I was just trying to log the output of `generateModuleHash(key)` to make sure whatever I'm doing is working properly.
